services:
  
  #api:
    #image: api:prod
    #build:
     # dockerfile: ./backend/api/Dockerfile
    #entrypoint: uv run fastapi run api/main.py --root-path=/api --reload
    #env_file:
    #  - backend.env
    #ports:
    #  - 8080:8080
    #volumes:
    #  - ./backend/api:/app/api
    #  - ./backend/api/.vscode/:/app/.vscode
  #    - ./backend/shared_mcp:/app/shared_mcp
  

  mcp:
    image: mcp:prod
    build:
      dockerfile: ./backend/mcp/Dockerfile
    environment:
      - MCP_SERVER_PORT=${MCP_SERVER_PORT}
    ports:
      - ${MCP_SERVER_PORT}:${MCP_SERVER_PORT}
    volumes:
      - ./backend/mcp:/app/mcp
      - ./backend/shared_mcp:/app/shared_mcp

  youtube:
    image: youtube-mcp-server
    env_file:
      - ./envs/youtube.env
    environment:
      - YOUTUBE_MCP_SERVER_PORT=${MCP_SERVER_PORT}
    ports:
      - 5050:${MCP_SERVER_PORT}

  inspector:
    image: inspector:prod
    build:
      dockerfile: ./inspector/Dockerfile
    ports:
      - 6274:6274
      - 6277:6277

  nginx:
    image: nginx:1.26.3-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  
  aws:
    image: aws-mcp-server
    build:
      context: ./mcp-aws/AWS_CloudGuardMCP
      dockerfile: Dockerfile
    env_file:
      - ./envs/aws.env
    environment:
      - AWS_MCP_PORT=5010
    ports:
      - 5010:5010
    volumes:
      - ./mcp-aws/AWS_CloudGuardMCP:/app
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5010"]

  
  kubernetes:
    image: k8s-mcp-server
    build:
      context: ./mcp-k8s/k8s-mcp-server
      dockerfile: deploy/docker/Dockerfile
    environment:
      - K8S_MCP_SECURITY_MODE=permissive
      - K8S_MCP_TRANSPORT=sse
    volumes:
      - ~/.kube:/home/appuser/.kube:ro
    ports:
      - 8081:8000


